[project]
name = "search-tools"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "mcp[cli]>=1.9.4",
    "cased-kit",
    "networkx>=3.5",
    "scipy>=1.16.0",
]
